### ISSUE TITLE
Create CPU Count helper function

### ISSUE THREAD

**Issue by KyleEvers** [Pascal-0x90/findcdn#9]
# 🚀 Feature Proposal

Create helper function for getting the CPU count used for threading

## Motivation

The os function may fail to get a valid cpu count returning a none type

## Example

https://github.com/Pascal-0x90/findCDN/blob/0dd9c6367cbb86c6d6a3af9a74f9f958a58c9e93/src/findCDN/cdnEngine/cdnEngine.py#L63

https://github.com/Pascal-0x90/findCDN/blob/0dd9c6367cbb86c6d6a3af9a74f9f958a58c9e93/src/findCDN/cdnEngine/cdnEngine.py#L117

https://github.com/Pascal-0x90/findCDN/blob/0dd9c6367cbb86c6d6a3af9a74f9f958a58c9e93/src/findCDN/cdnEngine/cdnEngine.py#L129

To:
```
try:
    threads = int = min(32, os.cpu_count() + 4)
catch:
    # Tell the user invalid cpu count
    threads =  1
```

## Pitch
This will make the tool more modular and verbose by handling failed cpu counts.

**Comment by Pascal-0x90** [comment]
Instead of making a helper function, the way for deciding the amount of threads was handled upon chef object creation. Since the method for grab_cdn() is a local method for the Chef object, we can just let the thread count desired be set as a local variable to the object. 

```python
  1   # Determine thread count
  2   if threads:
  3       self.threads = threads
  4   else:
  5       cpu_count = os.cpu_count()
  6       if cpu_count is None:
  7           cpu_count = 0
  8   self.threads = min(32, cpu_count + 4)  # type: ignore
```

This is handled in 0fbcc674d946f5b3e32213a541651831b02e0e7e commit.

**Comment by Pascal-0x90** [comment]
Modified this decision. Instead of setting cpu_count to always be `min(32, cpu_count + 4)` If the `os.cpu_count()` returns 0, we give the user the ability to have more fine grain control if they have lower cpu count. If the amount is actually 1, we do not want to exceed. Therefore we make sure `self.threads` will be set to the result of cpu_count which when a type of `None` is returned from `os.cpu_count()`, we will just set to 1 thread. 

```python

        # Determine thread count
        # Determine thread count
        if threads:
        if threads:
            self.threads = threads
            self.threads = threads
        else:
        else:
            cpu_count = os.cpu_count()
            cpu_count = os.cpu_count()
            if cpu_count is None:
            if cpu_count is None:
                cpu_count = 0
                cpu_count = 1
            self.threads = min(32, cpu_count + 4)  # type: ignore
            self.threads = cpu_count  # type: ignore
```
In commit e0a528ac1531ec05e296d0ff256f7a4df1606dd2
